# Generated by Django 5.1 on 2024-08-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_menu_delete_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='localidade',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
